# Basic GitLab CI/CD Pipeline
stages:
  - test
  - deploy

test:
  stage: test
  image: alpine:latest
  script:
    - echo "Testing ML Portfolio Projects"
    - echo "All projects ready"
  only:
    - master

pages:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Creating ML Portfolio Page"
    - mkdir -p public
    - echo "<!DOCTYPE html>" > public/index.html
    - echo "<html><head><title>Segni Mekonnen - ML Portfolio</title></head><body>" >> public/index.html
    - echo "<h1>Segni Mekonnen</h1>" >> public/index.html
    - echo "<h2>Machine Learning Engineer & Data Scientist</h2>" >> public/index.html
    - echo "<h3>Enhanced ML Portfolio Projects</h3>" >> public/index.html
    - echo "<p>Professional machine learning applications with advanced features.</p>" >> public/index.html
    - echo "<h4>Featured Projects:</h4>" >> public/index.html
    - echo "<ul>" >> public/index.html
    - echo "<li>Enhanced Internship Finder - 12 premium jobs</li>" >> public/index.html
    - echo "<li>Enhanced Sentiment Analyzer - Advanced NLP</li>" >> public/index.html
    - echo "<li>Enhanced Plant Disease Classifier - Professional CV</li>" >> public/index.html
    - echo "<li>Enhanced Interview Prep - Comprehensive tools</li>" >> public/index.html
    - echo "</ul>" >> public/index.html
    - echo "<h4>Deployment Status:</h4>" >> public/index.html
    - echo "<p>All projects enhanced with premium features</p>" >> public/index.html
    - echo "<p>Ready for Render deployment</p>" >> public/index.html
    - echo "<p>Professional portfolio created</p>" >> public/index.html
    - echo "<h4>Features:</h4>" >> public/index.html
    - echo "<ul>" >> public/index.html
    - echo "<li>12 Premium Internship Opportunities</li>" >> public/index.html
    - echo "<li>Advanced Search & Filtering</li>" >> public/index.html
    - echo "<li>Analytics Dashboards</li>" >> public/index.html
    - echo "<li>Real-time Processing</li>" >> public/index.html
    - echo "<li>Professional UI/UX</li>" >> public/index.html
    - echo "</ul>" >> public/index.html
    - echo "<p>All projects are enhanced and ready for production deployment!</p>" >> public/index.html
    - echo "</body></html>" >> public/index.html
    - echo "Portfolio created successfully"
  artifacts:
    paths:
      - public
  only:
    - master 