#!/bin/bash

echo "🚀 ML Projects Deployment Script"
echo "================================"
echo ""

echo "📋 Step 1: Create GitHub Repository"
echo "-----------------------------------"
echo "1. Go to https://github.com"
echo "2. Click '+' → 'New repository'"
echo "3. Repository name: budget-buddy"
echo "4. Description: ML Projects Portfolio"
echo "5. Make it Public ✅"
echo "6. Don't initialize with README"
echo "7. Click 'Create repository'"
echo ""

echo "📋 Step 2: Push Code to GitHub"
echo "------------------------------"
echo "After creating the repository, run:"
echo "git push -u origin master"
echo ""

echo "📋 Step 3: Deploy to Streamlit Cloud"
echo "------------------------------------"
echo "1. Go to https://streamlit.io/cloud"
echo "2. Sign in with GitHub"
echo "3. Click 'New app'"
echo ""

echo "🌐 Deploy These 4 Projects:"
echo ""

echo "Project 1: Interview Prep"
echo "- Repository: segnimekonnen7/budget-buddy"
echo "- Branch: master"
echo "- Main file: ml-projects/interview-prep/streamlit_app.py"
echo ""

echo "Project 2: Sentiment Analyzer"
echo "- Repository: segnimekonnen7/budget-buddy"
echo "- Branch: master"
echo "- Main file: ml-projects/sentiment-analyzer/streamlit_app.py"
echo ""

echo "Project 3: Internship Finder"
echo "- Repository: segnimekonnen7/budget-buddy"
echo "- Branch: master"
echo "- Main file: ml-projects/internship-finder/streamlit_app.py"
echo ""

echo "Project 4: Plant Disease Classifier"
echo "- Repository: segnimekonnen7/budget-buddy"
echo "- Branch: master"
echo "- Main file: ml-projects/image-classifier/streamlit_app.py"
echo ""

echo "🎯 After Deployment:"
echo "-------------------"
echo "You'll get URLs like:"
echo "- https://interview-prep-xxx.streamlit.app"
echo "- https://sentiment-analyzer-xxx.streamlit.app"
echo "- https://internship-finder-xxx.streamlit.app"
echo "- https://plant-classifier-xxx.streamlit.app"
echo ""

echo "📊 Your Complete Portfolio:"
echo "--------------------------"
echo "✅ Portfolio: https://segnimekonnen7.github.io/segni-portfolio-"
echo "✅ GitHub: https://github.com/segnimekonnen7/budget-buddy"
echo "✅ Live Demos: 4 Streamlit apps"
echo ""

echo "🚀 Ready to deploy! Follow the steps above." 